# Generated by Django 5.2.15 on 2026-06-04 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_intentado', models.EmailField(max_length=254, verbose_name='email intentado')),
                ('exito', models.BooleanField(default=False, verbose_name='éxito')),
                ('via', models.CharField(choices=[('PORTAL', 'Portal (frontend / API)'), ('ADMIN', 'Admin de Django')], default='PORTAL', max_length=10)),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='navegador / dispositivo')),
                ('pais', models.CharField(blank=True, max_length=100, verbose_name='país')),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='fecha y hora')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario real, si el email corresponde a una cuenta existente.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accesos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'registro de acceso',
                'verbose_name_plural': 'registros de acceso',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['email_intentado'], name='accounts_re_email_i_b2867b_idx'), models.Index(fields=['-creado_en'], name='accounts_re_creado__562b7e_idx')],
            },
        ),
    ]
