# Generated by Django 5.2.15 on 2026-06-04 19:09

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_remove_customuser_first_name_and_more'),
        ('core', '0001_initial'),
        ('gobierno', '0002_alter_organo_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PuntoOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='modificado en')),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('eliminado_en', models.DateTimeField(blank=True, editable=False, null=True)),
                ('orden', models.PositiveIntegerField(help_text='Posición en el orden del día (1, 2, 3...).')),
                ('titulo', models.CharField(max_length=255, verbose_name='título')),
                ('desarrollo', models.TextField(blank=True, help_text='Lo que se trató en el punto. Puede generarse/asistirse con IA.')),
                ('notas_crudas', models.TextField(blank=True, help_text='Material en bruto (apuntes, transcripción) como insumo para redactar el desarrollo.', verbose_name='notas crudas')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('TRATADO', 'Tratado'), ('POSPUESTO', 'Pospuesto'), ('INFORMATIVO', 'Informativo')], default='PENDIENTE', max_length=20)),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('eliminado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_eliminados', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por')),
                ('empresa', models.ForeignKey(blank=True, help_text='Empresa sobre la que trata el punto (opcional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puntos_tratados', to='core.empresa')),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
            ],
            options={
                'verbose_name': 'punto del orden del día',
                'verbose_name_plural': 'puntos del orden del día',
                'ordering': ['reunion', 'orden'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('todos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Resolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='modificado en')),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('eliminado_en', models.DateTimeField(blank=True, editable=False, null=True)),
                ('texto', models.TextField(help_text='El acuerdo tal como queda en el acta.')),
                ('resultado', models.CharField(choices=[('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('POSPUESTA', 'Pospuesta')], default='APROBADA', max_length=20)),
                ('por_unanimidad', models.BooleanField(default=True, verbose_name='por unanimidad')),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('eliminado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_eliminados', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por')),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
                ('punto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resoluciones', to='reuniones.puntoorden')),
            ],
            options={
                'verbose_name': 'resolución',
                'verbose_name_plural': 'resoluciones',
                'ordering': ['punto', 'id'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('todos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='puntoorden',
            name='viene_de',
            field=models.ForeignKey(blank=True, help_text='Resolución anterior a la que este punto da seguimiento (opcional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puntos_seguimiento', to='reuniones.resolucion'),
        ),
        migrations.CreateModel(
            name='Compromiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='modificado en')),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('eliminado_en', models.DateTimeField(blank=True, editable=False, null=True)),
                ('descripcion', models.TextField(verbose_name='descripción')),
                ('fecha_limite', models.DateField(blank=True, null=True, verbose_name='fecha límite')),
                ('para_proxima_reunion', models.BooleanField(default=False, verbose_name='para la próxima reunión')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CUMPLIDO', 'Cumplido'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('eliminado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_eliminados', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por')),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compromisos', to='accounts.persona')),
                ('punto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compromisos', to='reuniones.puntoorden')),
                ('resolucion', models.ForeignKey(blank=True, help_text='Resolución de la que nace el compromiso (opcional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compromisos', to='reuniones.resolucion')),
            ],
            options={
                'verbose_name': 'compromiso',
                'verbose_name_plural': 'compromisos',
                'ordering': ['estado', 'fecha_limite'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('todos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='modificado en')),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('eliminado_en', models.DateTimeField(blank=True, editable=False, null=True)),
                ('numero', models.PositiveIntegerField(help_text='Correlativo dentro de la gestión (ej. 4 para "Nº 04/2026").', verbose_name='número')),
                ('gestion', models.PositiveIntegerField(help_text='Año de la gestión (ej. 2026).', verbose_name='gestión')),
                ('fecha', models.DateField(verbose_name='fecha de inicio')),
                ('fecha_fin', models.DateField(blank=True, help_text='Solo si la reunión abarcó más de un día (cuarto intermedio).', null=True, verbose_name='fecha de fin')),
                ('hora_inicio', models.TimeField(blank=True, null=True, verbose_name='hora de inicio')),
                ('hora_fin', models.TimeField(blank=True, null=True, verbose_name='hora de fin')),
                ('lugar', models.CharField(blank=True, max_length=255)),
                ('tipo', models.CharField(choices=[('ORDINARIA', 'Ordinaria'), ('EXTRAORDINARIA', 'Extraordinaria')], default='ORDINARIA', max_length=20)),
                ('modalidad', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('VIRTUAL', 'Virtual'), ('MIXTA', 'Mixta')], default='PRESENCIAL', max_length=20)),
                ('estado', models.CharField(choices=[('CONVOCADA', 'Convocada'), ('REALIZADA', 'Realizada'), ('CANCELADA', 'Cancelada')], default='CONVOCADA', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('eliminado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_eliminados', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por')),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
                ('organo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reuniones', to='gobierno.organo')),
            ],
            options={
                'verbose_name': 'reunión',
                'verbose_name_plural': 'reuniones',
                'ordering': ['-gestion', '-numero'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('todos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='puntoorden',
            name='reunion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos', to='reuniones.reunion'),
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='modificado en')),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('eliminado_en', models.DateTimeField(blank=True, editable=False, null=True)),
                ('calidad', models.CharField(choices=[('MIEMBRO', 'Miembro del órgano'), ('SOCIO', 'Socio invitado'), ('SECRETARIO', 'Secretario de actas'), ('INVITADO', 'Invitado externo')], default='MIEMBRO', max_length=20)),
                ('estado', models.CharField(choices=[('PRESENTE', 'Presente'), ('AUSENTE', 'Ausente'), ('EXCUSA', 'Con excusa'), ('DELEGO', 'Delegó')], default='PRESENTE', max_length=20)),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('eliminado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_eliminados', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por')),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asistencias', to='accounts.persona')),
                ('reunion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='reuniones.reunion')),
            ],
            options={
                'verbose_name': 'asistencia',
                'verbose_name_plural': 'asistencias',
                'ordering': ['reunion', 'persona'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('todos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Acta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='modificado en')),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('eliminado_en', models.DateTimeField(blank=True, editable=False, null=True)),
                ('contenido', models.TextField(blank=True, help_text='Texto completo del acta. Puede generarse/asistirse con IA.')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('APROBADA', 'Aprobada'), ('FIRMADA', 'Firmada')], default='BORRADOR', max_length=20)),
                ('fecha_aprobacion', models.DateField(blank=True, null=True, verbose_name='fecha de aprobación')),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('eliminado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_eliminados', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por')),
                ('firmada_por', models.ManyToManyField(blank=True, help_text='Personas que suscribieron el acta.', related_name='actas_firmadas', to='accounts.persona')),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
                ('redactada_por', models.ForeignKey(blank=True, help_text='Secretario que redacta el acta.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actas_redactadas', to='accounts.persona')),
                ('reunion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acta', to='reuniones.reunion')),
            ],
            options={
                'verbose_name': 'acta',
                'verbose_name_plural': 'actas',
                'ordering': ['-reunion__gestion', '-reunion__numero'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('todos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='reunion',
            constraint=models.UniqueConstraint(condition=models.Q(('eliminado', False)), fields=('organo', 'gestion', 'numero'), name='unique_numero_reunion_por_organo_gestion'),
        ),
        migrations.AddConstraint(
            model_name='puntoorden',
            constraint=models.UniqueConstraint(condition=models.Q(('eliminado', False)), fields=('reunion', 'orden'), name='unique_orden_por_reunion'),
        ),
        migrations.AddConstraint(
            model_name='asistencia',
            constraint=models.UniqueConstraint(condition=models.Q(('eliminado', False)), fields=('reunion', 'persona'), name='unique_persona_por_reunion'),
        ),
    ]
