# Generated by Django 5.2.15 on 2026-06-04 19:40

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gobierno', '0002_alter_organo_tipo'),
        ('reuniones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PuntoRecurrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='modificado en')),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('eliminado_en', models.DateTimeField(blank=True, editable=False, null=True)),
                ('orden', models.PositiveIntegerField(help_text='Posición sugerida en el orden del día.')),
                ('titulo', models.CharField(max_length=255, verbose_name='título')),
                ('descripcion', models.TextField(blank=True, help_text='Nota guía de qué trata el punto (opcional).', verbose_name='descripción')),
                ('activo', models.BooleanField(default=True, help_text='Desmarcá para excluirlo sin borrarlo.')),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('eliminado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_eliminados', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por')),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
                ('organo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos_recurrentes', to='gobierno.organo')),
            ],
            options={
                'verbose_name': 'punto recurrente',
                'verbose_name_plural': 'puntos recurrentes (plantilla)',
                'ordering': ['organo', 'orden'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('eliminado', False)), fields=('organo', 'orden'), name='unique_orden_recurrente_por_organo')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('todos', django.db.models.manager.Manager()),
            ],
        ),
    ]
