# Generated by Django 5.2.15 on 2026-06-04 19:50

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import reuniones.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('reuniones', '0002_puntorecurrente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='modificado en')),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('eliminado_en', models.DateTimeField(blank=True, editable=False, null=True)),
                ('titulo', models.CharField(max_length=255, verbose_name='título')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('tipo', models.CharField(choices=[('ACTA_FIRMADA', 'Acta firmada'), ('INFORME', 'Informe'), ('CONTRATO', 'Contrato'), ('TESTIMONIO', 'Testimonio / escritura'), ('ESTADO_FINANCIERO', 'Estado financiero'), ('OTRO', 'Otro')], default='OTRO', max_length=20)),
                ('archivo', models.FileField(help_text='Archivo respaldatorio (PDF, Word, Excel o imagen).', upload_to=reuniones.models.documento_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png']), reuniones.models.validar_tamano_archivo])),
                ('hash_sha256', models.CharField(blank=True, editable=False, help_text='Huella de integridad calculada automáticamente al subir el archivo.', max_length=64, verbose_name='hash SHA-256')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='fecha del documento')),
                ('acta', models.ForeignKey(blank=True, help_text='Acta a la que respalda este documento (opcional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='reuniones.acta')),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('eliminado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_eliminados', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por')),
                ('empresa', models.ForeignKey(blank=True, help_text='Empresa a la que pertenece el documento (opcional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='core.empresa')),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
                ('punto', models.ForeignKey(blank=True, help_text='Punto del orden del día al que pertenece (opcional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='reuniones.puntoorden')),
            ],
            options={
                'verbose_name': 'documento',
                'verbose_name_plural': 'documentos',
                'ordering': ['-fecha', '-creado_en'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('todos', django.db.models.manager.Manager()),
            ],
        ),
    ]
