# Generated by Django 5.2.15 on 2026-06-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reuniones', '0004_grupo_gestores_compromisos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compromiso',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Por hacer'), ('EN_PROCESO', 'En proceso'), ('CUMPLIDO', 'Realizado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20),
        ),
    ]
