# Generated by Django 5.2.15 on 2026-06-05 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reuniones', '0006_grupo_gestores_reuniones'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroDescarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Snapshot del título en el momento del acceso; persiste aunque el documento se elimine.', max_length=255, verbose_name='título')),
                ('accion', models.CharField(choices=[('SUBIDA', 'Subida'), ('DESCARGA', 'Descarga'), ('ELIMINACION', 'Eliminación')], max_length=12, verbose_name='acción')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='dirección IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
                ('documento', models.ForeignKey(blank=True, help_text='Puede quedar nulo si el documento es borrado físicamente del sistema.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros', to='reuniones.documento', verbose_name='documento')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_documentos', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'registro de acceso a documento',
                'verbose_name_plural': 'registros de acceso a documentos',
                'ordering': ['-fecha'],
            },
        ),
    ]
