# Generated by Django 5.2.15 on 2026-06-06 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reuniones', '0007_registrodescarga'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntoorden',
            name='resumen',
            field=models.TextField(blank=True, help_text='Síntesis concisa de los aspectos más relevantes tratados. Generado/asistido por IA.', verbose_name='resumen'),
        ),
        migrations.AlterField(
            model_name='puntoorden',
            name='desarrollo',
            field=models.TextField(blank=True, help_text='Texto del acta para este punto, limpiado ortográficamente pero sin resumir. Puede generarse/asistirse con IA.'),
        ),
    ]
