# Generated by Django 5.2.15 on 2026-06-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gobierno', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organo',
            name='tipo',
            field=models.CharField(choices=[('DIRECTORIO', 'Directorio'), ('COMITE', 'Comité')], max_length=20),
        ),
    ]
