# Generated by Django 5.2.15 on 2026-06-07 15:01

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='modificado en')),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('eliminado_en', models.DateTimeField(blank=True, editable=False, null=True)),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('categoria', models.CharField(choices=[('INMUEBLE', 'Inmueble'), ('VEHICULO', 'Vehículo'), ('MAQUINARIA', 'Maquinaria / Equipo')], max_length=20, verbose_name='categoría')),
                ('tipo', models.CharField(choices=[('LOTE', 'Lote'), ('CASA', 'Casa'), ('DEPARTAMENTO', 'Departamento'), ('LOCAL', 'Local comercial'), ('OFICINA', 'Oficina'), ('TERRENO', 'Terreno'), ('AUTO', 'Automóvil'), ('MOTO', 'Motocicleta'), ('CAMION', 'Camión / Furgoneta'), ('MINIBUS', 'Minibús'), ('MAQUINARIA_PESADA', 'Maquinaria pesada'), ('EQUIPO', 'Equipo / Herramienta')], max_length=20, verbose_name='tipo')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('EN_MANTENIMIENTO', 'En mantenimiento'), ('VENDIDO', 'Vendido'), ('BAJA', 'Baja')], default='ACTIVO', max_length=20, verbose_name='estado')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='valor (Bs.)')),
                ('fecha_adquisicion', models.DateField(blank=True, null=True, verbose_name='fecha de adquisición')),
                ('notas', models.TextField(blank=True, verbose_name='notas')),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitud')),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitud')),
                ('direccion', models.CharField(blank=True, max_length=300, verbose_name='dirección')),
                ('area_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='área (m²)')),
                ('nro_catastral', models.CharField(blank=True, max_length=100, verbose_name='N° catastral')),
                ('nro_habitaciones', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='N° habitaciones')),
                ('placa', models.CharField(blank=True, max_length=20, verbose_name='placa / matrícula')),
                ('marca', models.CharField(blank=True, max_length=100, verbose_name='marca')),
                ('modelo_descripcion', models.CharField(blank=True, max_length=100, verbose_name='modelo')),
                ('anio', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='año')),
                ('nro_serie', models.CharField(blank=True, max_length=100, verbose_name='N° de serie / chasis')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='color')),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('eliminado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_eliminados', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activos', to='core.empresa', verbose_name='empresa')),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
            ],
            options={
                'verbose_name': 'activo',
                'verbose_name_plural': 'activos',
                'ordering': ['empresa', 'categoria', 'nombre'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('todos', django.db.models.manager.Manager()),
            ],
        ),
    ]
