# Generated by Django 5.2.15 on 2026-06-09 06:19

import activos.models
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0001_crear_activo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, verbose_name='ciudad'),
        ),
        migrations.AddField(
            model_name='activo',
            name='departamento',
            field=models.CharField(blank=True, max_length=100, verbose_name='departamento'),
        ),
        migrations.AddField(
            model_name='activo',
            name='estado_inmueble',
            field=models.CharField(blank=True, choices=[('SIN_PROYECTO', 'Sin proyecto'), ('POR_REGULARIZAR', 'Por regularizar'), ('EN_PROYECTO', 'En proyecto'), ('PROYECTO_TERMINADO', 'Proyecto terminado')], default='SIN_PROYECTO', max_length=25, verbose_name='estado del inmueble'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='area_m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='área (m²)'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='valor (USD)'),
        ),
        migrations.CreateModel(
            name='ActivoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='modificado en')),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('eliminado_en', models.DateTimeField(blank=True, editable=False, null=True)),
                ('titulo', models.CharField(blank=True, help_text='Descripción breve del documento (opcional).', max_length=200, verbose_name='título / descripción')),
                ('archivo', models.FileField(help_text='PDF, imagen u otro formato. Máx. 30 MB.', max_length=300, upload_to=activos.models.activo_documento_upload_to, verbose_name='archivo')),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='activos.activo', verbose_name='activo')),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('eliminado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_eliminados', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por')),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
            ],
            options={
                'verbose_name': 'documento de activo',
                'verbose_name_plural': 'documentos de activos',
                'ordering': ['-creado_en'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('todos', django.db.models.manager.Manager()),
            ],
        ),
    ]
