# Generated by Django 5.2.15 on 2026-06-04 17:01

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='modificado en')),
                ('eliminado', models.BooleanField(default=False, editable=False)),
                ('eliminado_en', models.DateTimeField(blank=True, editable=False, null=True)),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='código')),
                ('activa', models.BooleanField(default=True)),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('eliminado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_eliminados', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por')),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
                'ordering': ['nombre'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('todos', django.db.models.manager.Manager()),
            ],
        ),
    ]
